spring:
  datasource:
    # db source url
    url: jdbc:mysql://localhost:3306/fc-sb-admin?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    # db response name
    username: root
    # db response password
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  devtools:
    livereload:
      enabled: false